// <auto-generated />
using System;
using CoachBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoachBot.Domain.Migrations
{
    [DbContext(typeof(CoachBotContext))]
    [Migration("20200824182904_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoachBot.Domain.Model.AssetImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Base64EncodedImage");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FileName");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("AssetImages");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelType");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("DisableSearchNotifications");

                    b.Property<decimal>("DiscordChannelId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("DiscordChannelName");

                    b.Property<bool>("DuplicityProtection");

                    b.Property<int>("Formation");

                    b.Property<bool>("Inactive");

                    b.Property<string>("SearchIgnoreList");

                    b.Property<string>("SubTeamCode");

                    b.Property<string>("SubTeamName");

                    b.Property<int>("TeamId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<bool>("UseClassicLineup");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DiscordChannelId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ChannelPosition", b =>
                {
                    b.Property<int>("ChannelId");

                    b.Property<int>("PositionId");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Ordinal");

                    b.HasKey("ChannelId", "PositionId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PositionId");

                    b.ToTable("ChannelPositions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("PositionGroup");

                    b.Property<double>("Rating");

                    b.Property<int?>("TeamId");

                    b.Property<int?>("TournamentId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("FantasyPlayers");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyPlayerPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FantasyPlayerId");

                    b.Property<int?>("PlayerMatchStatisticsId");

                    b.Property<int>("Points");

                    b.Property<int>("PositionGroup");

                    b.Property<int?>("TournamentPhaseId");

                    b.HasKey("Id");

                    b.HasIndex("FantasyPlayerId");

                    b.HasIndex("PlayerMatchStatisticsId");

                    b.HasIndex("TournamentPhaseId");

                    b.ToTable("FantasyPlayerPhases");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("PlayerId");

                    b.Property<int?>("TournamentId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("PlayerId", "TournamentId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL AND [TournamentId] IS NOT NULL");

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyTeamSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("FantasyPlayerId");

                    b.Property<int?>("FantasyTeamId");

                    b.Property<bool>("IsFlex");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FantasyPlayerId");

                    b.HasIndex("FantasyTeamId");

                    b.ToTable("FantasyTeamSelections");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Format");

                    b.Property<DateTime?>("KickOff");

                    b.Property<int?>("MapId");

                    b.Property<int?>("MatchStatisticsId");

                    b.Property<int>("MatchType");

                    b.Property<int?>("ServerId");

                    b.Property<int?>("TeamAwayId");

                    b.Property<int?>("TeamHomeId");

                    b.Property<int?>("TournamentId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MapId");

                    b.HasIndex("MatchStatisticsId");

                    b.HasIndex("ServerId");

                    b.HasIndex("TeamAwayId");

                    b.HasIndex("TeamHomeId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.MatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwayGoals");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("HomeGoals");

                    b.Property<string>("MatchData");

                    b.Property<string>("SourceAddress");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Matchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("LineupAwayId");

                    b.Property<int?>("LineupHomeId");

                    b.Property<int?>("MatchId");

                    b.Property<DateTime?>("ReadiedDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("LineupAwayId")
                        .IsUnique()
                        .HasFilter("[LineupAwayId] IS NOT NULL");

                    b.HasIndex("LineupHomeId")
                        .IsUnique()
                        .HasFilter("[LineupHomeId] IS NOT NULL");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasFilter("[MatchId] IS NOT NULL");

                    b.ToTable("Matchups");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym");

                    b.Property<string>("BrandColour");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("LogoImageId");

                    b.Property<string>("Name");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LogoImageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerLineupPosition", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("PositionId");

                    b.Property<int>("LineupId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("PlayerId", "PositionId", "LineupId");

                    b.HasIndex("LineupId");

                    b.HasIndex("PositionId", "LineupId")
                        .IsUnique();

                    b.ToTable("PlayerLineupPositions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerLineupSubstitute", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("LineupId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("PlayerId", "LineupId");

                    b.HasIndex("LineupId");

                    b.ToTable("PlayerLineupSubstitutes");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerMatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists");

                    b.Property<int>("Corners");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DistanceCovered");

                    b.Property<int>("Fouls");

                    b.Property<int>("FoulsSuffered");

                    b.Property<int>("FreeKicks");

                    b.Property<int>("GoalKicks");

                    b.Property<int>("Goals");

                    b.Property<int>("GoalsConceded");

                    b.Property<int>("Interceptions");

                    b.Property<int>("KeeperSaves");

                    b.Property<int>("KeeperSavesCaught");

                    b.Property<int>("MatchId");

                    b.Property<int>("MatchOutcome");

                    b.Property<int>("MatchTeamType");

                    b.Property<string>("Nickname");

                    b.Property<int>("Offsides");

                    b.Property<int>("OwnGoals");

                    b.Property<int>("Passes");

                    b.Property<int>("PassesCompleted");

                    b.Property<int>("Penalties");

                    b.Property<int>("PlayerId");

                    b.Property<int>("Possession");

                    b.Property<int>("PossessionPercentage");

                    b.Property<int>("RedCards");

                    b.Property<int>("SecondsPlayed");

                    b.Property<int>("Shots");

                    b.Property<int>("ShotsOnGoal");

                    b.Property<int>("SlidingTackles");

                    b.Property<int>("SlidingTacklesCompleted");

                    b.Property<bool>("Substitute");

                    b.Property<int?>("TeamId");

                    b.Property<int>("ThrowIns");

                    b.Property<int>("YellowCards");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerMatchStatistics");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerPosition", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("PositionId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("PlayerId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerPositions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerPositionMatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists");

                    b.Property<int>("Corners");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DistanceCovered");

                    b.Property<int>("Fouls");

                    b.Property<int>("FoulsSuffered");

                    b.Property<int>("FreeKicks");

                    b.Property<int>("GoalKicks");

                    b.Property<int>("Goals");

                    b.Property<int>("GoalsConceded");

                    b.Property<int>("Interceptions");

                    b.Property<int>("KeeperSaves");

                    b.Property<int>("KeeperSavesCaught");

                    b.Property<int>("MatchId");

                    b.Property<int>("MatchOutcome");

                    b.Property<int>("MatchTeamType");

                    b.Property<string>("Nickname");

                    b.Property<int>("Offsides");

                    b.Property<int>("OwnGoals");

                    b.Property<int>("Passes");

                    b.Property<int>("PassesCompleted");

                    b.Property<int>("Penalties");

                    b.Property<int>("PlayerId");

                    b.Property<int?>("PositionId");

                    b.Property<int>("Possession");

                    b.Property<int>("PossessionPercentage");

                    b.Property<int>("RedCards");

                    b.Property<int>("SecondsPlayed");

                    b.Property<int>("Shots");

                    b.Property<int>("ShotsOnGoal");

                    b.Property<int>("SlidingTackles");

                    b.Property<int>("SlidingTacklesCompleted");

                    b.Property<bool>("Substitute");

                    b.Property<int?>("TeamId");

                    b.Property<int>("ThrowIns");

                    b.Property<int>("YellowCards");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerPositionMatchStatistics");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("PlayerId");

                    b.Property<double>("Rating");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsPending");

                    b.Property<DateTime>("JoinDate");

                    b.Property<DateTime?>("LeaveDate");

                    b.Property<int>("PlayerId");

                    b.Property<int>("TeamId");

                    b.Property<int>("TeamRole");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PlayerTeams");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ScorePrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayGoalsPrediction");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("HomeGoalsPrediction");

                    b.Property<int>("MatchId");

                    b.Property<int>("PlayerId");

                    b.Property<int?>("TournamentPhaseId");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentPhaseId");

                    b.ToTable("ScorePredictions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DiscordSearchMessages");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.SubstitutionRequest", b =>
                {
                    b.Property<string>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AcceptedById");

                    b.Property<DateTime?>("AcceptedDate");

                    b.Property<int>("ChannelId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("DiscordMessageId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("ServerId");

                    b.HasKey("Token");

                    b.HasIndex("AcceptedById");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ServerId");

                    b.ToTable("SubstitutionRequests");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeEmote");

                    b.Property<int?>("BadgeImageId");

                    b.Property<string>("Color");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Form");

                    b.Property<DateTime?>("FoundedDate");

                    b.Property<int?>("GuildId");

                    b.Property<bool>("Inactive");

                    b.Property<string>("KitEmote");

                    b.Property<string>("Name")
                        .HasMaxLength(40);

                    b.Property<int?>("RegionId");

                    b.Property<string>("TeamCode")
                        .HasMaxLength(6);

                    b.Property<int>("TeamType");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BadgeImageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GuildId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("TeamCode", "RegionId")
                        .IsUnique()
                        .HasFilter("[TeamCode] IS NOT NULL AND [RegionId] IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TeamMatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists");

                    b.Property<int>("Corners");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DistanceCovered");

                    b.Property<int>("Fouls");

                    b.Property<int>("FoulsSuffered");

                    b.Property<int>("FreeKicks");

                    b.Property<int>("GoalKicks");

                    b.Property<int>("Goals");

                    b.Property<int>("GoalsConceded");

                    b.Property<int>("Interceptions");

                    b.Property<int>("KeeperSaves");

                    b.Property<int>("KeeperSavesCaught");

                    b.Property<int>("MatchId");

                    b.Property<int>("MatchOutcome");

                    b.Property<int>("MatchTeamType");

                    b.Property<int>("Offsides");

                    b.Property<int>("OwnGoals");

                    b.Property<int>("Passes");

                    b.Property<int>("PassesCompleted");

                    b.Property<int>("Penalties");

                    b.Property<int>("Possession");

                    b.Property<int>("PossessionPercentage");

                    b.Property<int>("RedCards");

                    b.Property<int>("Shots");

                    b.Property<int>("ShotsOnGoal");

                    b.Property<int>("SlidingTackles");

                    b.Property<int>("SlidingTacklesCompleted");

                    b.Property<int?>("TeamId");

                    b.Property<string>("TeamName");

                    b.Property<int>("ThrowIns");

                    b.Property<int>("YellowCards");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMatchStatistics");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("FantasyPointsLimit");

                    b.Property<int>("Format");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("TeamType");

                    b.Property<int>("TournamentSeriesId");

                    b.Property<int>("TournamentType");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int?>("WinningTeamId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TournamentSeriesId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name");

                    b.Property<int?>("TournamentStageId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TournamentStageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TournamentGroups");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroupMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MatchId");

                    b.Property<string>("TeamAwayPlaceholder");

                    b.Property<string>("TeamHomePlaceholder");

                    b.Property<int>("TournamentGroupId");

                    b.Property<int>("TournamentPhaseId");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TournamentGroupId");

                    b.HasIndex("TournamentPhaseId");

                    b.ToTable("TournamentGroupMatches");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroupTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TeamId");

                    b.Property<int>("TournamentGroupId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentGroupId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TournamentGroupTeams");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentMatchDaySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MatchDay");

                    b.Property<DateTime>("MatchTime");

                    b.Property<int>("TournamentId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TournamentMatchDays");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name");

                    b.Property<int>("TournamentStageId");

                    b.HasKey("Id");

                    b.HasIndex("TournamentStageId");

                    b.ToTable("TournamentPhases");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name");

                    b.Property<int>("OrganisationId");

                    b.Property<int?>("TournamentLogoId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TournamentLogoId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TournamentSeries");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PlayerId");

                    b.Property<int>("Role");

                    b.Property<int?>("TournamentId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("PlayerId", "TournamentId")
                        .IsUnique()
                        .HasFilter("[TournamentId] IS NOT NULL");

                    b.ToTable("TournamentStaff");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name");

                    b.Property<int>("TournamentId");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentStages");
                });

            modelBuilder.Entity("CoachBot.Model.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("DiscordGuildId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("IconUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("CoachBot.Model.Lineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChannelId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TeamType");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("CoachBot.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("DisableDMNotifications");

                    b.Property<decimal?>("DiscordUserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("HubRole");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("PlayingSince");

                    b.Property<double>("Rating");

                    b.Property<decimal?>("SteamID")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasFilter("[DiscordUserId] IS NOT NULL");

                    b.HasIndex("SteamID")
                        .IsUnique()
                        .HasFilter("[SteamID] IS NOT NULL");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CoachBot.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("CoachBot.Model.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RegionCode");

                    b.Property<string>("RegionName");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionName")
                        .IsUnique()
                        .HasFilter("[RegionName] IS NOT NULL");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CoachBot.Model.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("CountryId");

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeactivatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .HasMaxLength(40);

                    b.Property<string>("RconPassword");

                    b.Property<int>("RegionId");

                    b.Property<int?>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RegionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.AssetImage", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Channel", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany("Channels")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ChannelPosition", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany("ChannelPositions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany("ChannelPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyPlayer", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyPlayerPhase", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.FantasyPlayer", "FantasyPlayer")
                        .WithMany("Phases")
                        .HasForeignKey("FantasyPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.PlayerMatchStatistics", "PlayerMatchStatistics")
                        .WithMany()
                        .HasForeignKey("PlayerMatchStatisticsId");

                    b.HasOne("CoachBot.Domain.Model.TournamentPhase", "TournamentPhase")
                        .WithMany()
                        .HasForeignKey("TournamentPhaseId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyTeam", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.FantasyTeamSelection", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.FantasyPlayer", "FantasyPlayer")
                        .WithMany()
                        .HasForeignKey("FantasyPlayerId");

                    b.HasOne("CoachBot.Domain.Model.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamSelections")
                        .HasForeignKey("FantasyTeamId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Match", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");

                    b.HasOne("CoachBot.Domain.Model.MatchStatistics", "MatchStatistics")
                        .WithMany()
                        .HasForeignKey("MatchStatisticsId");

                    b.HasOne("CoachBot.Model.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.HasOne("CoachBot.Domain.Model.Team", "TeamAway")
                        .WithMany()
                        .HasForeignKey("TeamAwayId");

                    b.HasOne("CoachBot.Domain.Model.Team", "TeamHome")
                        .WithMany()
                        .HasForeignKey("TeamHomeId");

                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Matchup", b =>
                {
                    b.HasOne("CoachBot.Model.Lineup", "LineupAway")
                        .WithOne("AwayMatchup")
                        .HasForeignKey("CoachBot.Domain.Model.Matchup", "LineupAwayId");

                    b.HasOne("CoachBot.Model.Lineup", "LineupHome")
                        .WithOne("HomeMatchup")
                        .HasForeignKey("CoachBot.Domain.Model.Matchup", "LineupHomeId");

                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithOne("Matchup")
                        .HasForeignKey("CoachBot.Domain.Model.Matchup", "MatchId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Organisation", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.AssetImage", "LogoImage")
                        .WithMany()
                        .HasForeignKey("LogoImageId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerLineupPosition", b =>
                {
                    b.HasOne("CoachBot.Model.Lineup", "Lineup")
                        .WithMany("PlayerLineupPositions")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("PlayerLineupPositions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany("PlayerLineupPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerLineupSubstitute", b =>
                {
                    b.HasOne("CoachBot.Model.Lineup", "Lineup")
                        .WithMany("PlayerSubstitutes")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("PlayerSubstitutes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerMatchStatistics", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany("PlayerMatchStatistics")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerPosition", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("Positions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerPositionMatchStatistics", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany("PlayerPositionMatchStatistics")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerRating", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeam", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany("CreatedPlayerTeams")
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("Teams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany("UpdatedPlayerTeams")
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ScorePrediction", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.TournamentPhase", "TournamentPhase")
                        .WithMany()
                        .HasForeignKey("TournamentPhaseId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Search", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.SubstitutionRequest", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "AcceptedBy")
                        .WithMany()
                        .HasForeignKey("AcceptedById");

                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Team", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.AssetImage", "BadgeImage")
                        .WithMany()
                        .HasForeignKey("BadgeImageId");

                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.HasOne("CoachBot.Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TeamMatchStatistics", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany("TeamMatchStatistics")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany("TeamMatchStatistics")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Tournament", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.TournamentSeries", "TournamentSeries")
                        .WithMany("Tournaments")
                        .HasForeignKey("TournamentSeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("CoachBot.Domain.Model.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroup", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.TournamentStage", "TournamentStage")
                        .WithMany("TournamentGroups")
                        .HasForeignKey("TournamentStageId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroupMatch", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.TournamentGroup", "TournamentGroup")
                        .WithMany("TournamentGroupMatches")
                        .HasForeignKey("TournamentGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.TournamentPhase", "TournamentPhase")
                        .WithMany("TournamentGroupMatches")
                        .HasForeignKey("TournamentPhaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentGroupTeam", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.TournamentGroup", "TournamentGroup")
                        .WithMany("TournamentGroupTeams")
                        .HasForeignKey("TournamentGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentMatchDaySlot", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany("TournamentMatchDays")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentPhase", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.TournamentStage", "TournamentStage")
                        .WithMany("TournamentPhases")
                        .HasForeignKey("TournamentStageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentSeries", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Domain.Model.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.AssetImage", "TournamentLogo")
                        .WithMany()
                        .HasForeignKey("TournamentLogoId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentStaff", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany("TournamentStaff")
                        .HasForeignKey("TournamentId");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.TournamentStage", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Tournament", "Tournament")
                        .WithMany("TournamentStages")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Model.Guild", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");
                });

            modelBuilder.Entity("CoachBot.Model.Lineup", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("CoachBot.Model.Player", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany("CreatedPlayers")
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany("UpdatedPlayers")
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("CoachBot.Model.Server", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CoachBot.Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Player", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });
#pragma warning restore 612, 618
        }
    }
}
