// <auto-generated />
using System;
using CoachBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoachBot.Domain.Migrations
{
    [DbContext(typeof(CoachBotContext))]
    [Migration("20191130194616_Migrati4on301112019")]
    partial class Migrati4on301112019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoachBot.Domain.Model.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeEmote");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("DisableSearchNotifications");

                    b.Property<decimal>("DiscordChannelId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("DiscordChannelName");

                    b.Property<bool>("DuplicityProtection");

                    b.Property<int>("Formation");

                    b.Property<int>("GuildId");

                    b.Property<bool>("Inactive");

                    b.Property<bool>("IsMixChannel");

                    b.Property<string>("KitEmote");

                    b.Property<string>("Name");

                    b.Property<int?>("RegionId");

                    b.Property<string>("TeamCode");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<bool>("UseClassicLineup");

                    b.HasKey("Id");

                    b.HasIndex("DiscordChannelId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("RegionId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ChannelPosition", b =>
                {
                    b.Property<int>("ChannelId");

                    b.Property<int>("PositionId");

                    b.HasKey("ChannelId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("ChannelPositions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 117,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 128,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 59,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 94,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 45,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 36,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 22,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 82,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 46,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 42,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 60,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 136,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 118,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 110,
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 101,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 85,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 44,
                            Code = "029",
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 20,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 28,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 61,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 83,
                            Code = "CD",
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 62,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 84,
                            Code = "CI",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 92,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 63,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 35,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 1,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 64,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 7,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 74,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 134,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 77,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 81,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 80,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 29,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 98,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 38,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 43,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 100,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 66,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 86,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 67,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 48,
                            Code = "HK",
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 93,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 95,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 21,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 49,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78,
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 8,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 50,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 91,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 96,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 51,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 97,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 9,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 99,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 131,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 102,
                            Code = "KR",
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 10,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 103,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 105,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 58,
                            Code = "419",
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 107,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 11,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 12,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 39,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 106,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 40,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MO",
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 108,
                            Code = "MK",
                            Name = "Macedonia, FYRO"
                        },
                        new
                        {
                            Id = 52,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 41,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 88,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 111,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 68,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 120,
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 87,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 109,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 129,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 112,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 114,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 90,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 53,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 69,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 26,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 113,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 14,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 115,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 70,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 73,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 71,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 54,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 116,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 119,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 72,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 15,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 89,
                            Code = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 121,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 23,
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 122,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 16,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 130,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 55,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 125,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 126,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 127,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 123,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 17,
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 142,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 132,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 133,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 56,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 18,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 137,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 135,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 138,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 34,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 32,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 75,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 139,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 76,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 140,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 104,
                            Code = "001",
                            Name = "World"
                        },
                        new
                        {
                            Id = 19,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 57,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("ReadiedDate");

                    b.Property<int?>("ServerId");

                    b.Property<int?>("TeamAwayId");

                    b.Property<int?>("TeamHomeId");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("TeamAwayId");

                    b.HasIndex("TeamHomeId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.MatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatchData");

                    b.Property<int>("MatchId");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeamPosition", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("PositionId");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId", "PositionId", "TeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("PositionId", "TeamId")
                        .IsUnique();

                    b.ToTable("PlayerTeamPositions");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeamSubstitute", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerTeamSubstitute");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DiscordMessageIds");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.SubstitutionRequest", b =>
                {
                    b.Property<string>("Token")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AcceptedById");

                    b.Property<DateTime?>("AcceptedDate");

                    b.Property<int>("ChannelId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("DiscordMessageId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<int>("ServerId");

                    b.HasKey("Token");

                    b.HasIndex("AcceptedById");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ServerId");

                    b.ToTable("SubstitutionRequests");
                });

            modelBuilder.Entity("CoachBot.Model.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DiscordGuildId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("CoachBot.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("DiscordUserId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("DiscordUserMention");

                    b.Property<string>("Name");

                    b.Property<string>("SteamID");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CoachBot.Model.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("CoachBot.Model.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RegionCode");

                    b.Property<string>("RegionName");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionName")
                        .IsUnique()
                        .HasFilter("[RegionName] IS NOT NULL");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CoachBot.Model.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("CountryId");

                    b.Property<string>("Name");

                    b.Property<string>("RconPassword");

                    b.Property<int>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("CoachBot.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChannelId");

                    b.Property<int>("TeamType");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Channel", b =>
                {
                    b.HasOne("CoachBot.Model.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.ChannelPosition", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany("ChannelPositions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany("ChannelPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Match", b =>
                {
                    b.HasOne("CoachBot.Model.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.HasOne("CoachBot.Model.Team", "TeamAway")
                        .WithMany()
                        .HasForeignKey("TeamAwayId");

                    b.HasOne("CoachBot.Model.Team", "TeamHome")
                        .WithMany()
                        .HasForeignKey("TeamHomeId");
                });

            modelBuilder.Entity("CoachBot.Domain.Model.MatchStatistics", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeamPosition", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("PlayerTeamPositions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Position", "Position")
                        .WithMany("PlayerTeamPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Team", "Team")
                        .WithMany("PlayerTeamPositions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.PlayerTeamSubstitute", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "Player")
                        .WithMany("PlayerSubstitutes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Team", "Team")
                        .WithMany("PlayerSubstitutes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.Search", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Domain.Model.SubstitutionRequest", b =>
                {
                    b.HasOne("CoachBot.Model.Player", "AcceptedBy")
                        .WithMany()
                        .HasForeignKey("AcceptedById");

                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoachBot.Model.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Model.Server", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoachBot.Model.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoachBot.Model.Team", b =>
                {
                    b.HasOne("CoachBot.Domain.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
