export enum StatisticType {
    RedCards = 0,
    YellowCards,
    Fouls,
    FoulsSuffered,
    SlidingTackles,
    SlidingTacklesCompleted,
    GoalsConceded,
    Shots,
    ShotsOnGoal,
    PassesCompleted,
    Interceptions,
    Offsides,
    Goals,
    OwnGoals,
    Assists,
    Passes,
    FreeKicks,
    Penalties,
    Corners,
    ThrowIns,
    KeeperSaves,
    GoalKicks,
    Possession,
    DistanceCovered,
    KeeperSavesCaught
}